[package]
name = "reservoir_sample"
version = "1.0.0"
edition = "2023"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8"
structopt = "0.3"
indicatif = "0.15.0"
